ARG EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
ARG FLAVOR=cpu
ARG HERMETIC=false

FROM registry.access.redhat.com/ubi9/python-311 as cpu-base
ARG EMBEDDING_MODEL
ARG FLAVOR

FROM nvcr.io/nvidia/cuda:12.6.3-devel-ubi9 as gpu-base
ARG EMBEDDING_MODEL
ARG FLAVOR
RUN dnf install -y python3.11 python3.11-pip libcudnn9 libnccl

FROM ${FLAVOR}-base as aap-rag-builder
ARG EMBEDDING_MODEL
ARG FLAVOR
ARG AAP_VERSION=2.5

USER 0
WORKDIR /workdir

COPY pyproject.toml pdm.lock.* Makefile .
RUN make install-tools && pdm config python.use_venv false && make pdm-lock-check install-deps

COPY additional_docs ./additional_docs

COPY scripts/download_embeddings_model.py .
RUN pdm run python download_embeddings_model.py -l ./embeddings_model -r ${EMBEDDING_MODEL}

RUN if [ "$FLAVOR" == "gpu" ]; then \
        export LD_LIBRARY_PATH=/usr/local/cuda-12.6/compat:$LD_LIBRARY_PATH; \
        pdm run python -c \
        "import torch; print(torch.version.cuda); print(torch.cuda.is_available());"; \
    fi

COPY scripts/download-mimir.sh .
RUN ./download-mimir.sh

COPY scripts/generate_embeddings-aap.py .
RUN export LD_LIBRARY_PATH=/usr/local/cuda-12.6/compat:$LD_LIBRARY_PATH; \
	set -e && pdm run python generate_embeddings-aap.py \
  -f red_hat_content \
  -mn ${EMBEDDING_MODEL} \
  -o vector_db/aap_product_docs/${AAP_VERSION} \
  -i aap-product-docs-$(echo $AAP_VERSION | sed 's/\./_/g') \
  -v ${AAP_VERSION}

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:b87097994ed62fbf1de70bc75debe8dacf3ea6e00dd577d74503ef66452c59d6
COPY --from=aap-rag-builder /workdir/vector_db/aap_product_docs /rag/vector_db/aap_product_docs
COPY --from=aap-rag-builder /workdir/embeddings_model /rag/embeddings_model

# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
RUN mkdir /licenses
COPY LICENSE /licenses/

# Labels for enterprise contract
LABEL com.redhat.component=aap-rag-content
LABEL description="Red Hat Ansible Automation Platform RAG content"
LABEL distribution-scope=private
LABEL io.k8s.description="Red Hat Ansible Automation Platform RAG content"
LABEL io.k8s.display-name="Ansible Automation Platform RAG content"
LABEL io.ansible.tags="ansible,aap,ai,assistant,rag"
LABEL name=aap-rag-content
LABEL release=0.0.1
LABEL url="https://github.com/ansible/aap-rag-content"
LABEL vendor="Red Hat"
LABEL version=0.0.1
LABEL summary="Red Hat Ansible Automation Platform RAG content"

USER 65532:65532
