# Note: This hash aligns with lightspeed-core/rag-content version 0.5.0.
FROM quay.io/lightspeed-core/rag-content-cpu@sha256:8816c11286ce4a260e5b7fbf9ee8b305459aab4458cef0ff7983dd6cb4502de7 as builder
ARG EMBEDDING_MODEL=sentence-transformers/all-mpnet-base-v2
ARG AAP_VERSION=2.6

WORKDIR /rag-content
USER 0

COPY aap-product-docs-plaintext ./aap-product-docs-plaintext
COPY additional_docs ./additional_docs
COPY solution-guides-plaintext ./solution-guides-plaintext

COPY scripts/custom_processor_aap.py .
COPY src/aap_rag_content ./aap_rag_content

RUN microdnf install -y gzip

ENV PYTHONPATH=/rag-content
RUN python custom_processor_aap.py  \
  -o ./llama_stack_vector_db \
  -f /rag-content \
  -md embeddings_model/ \
  -mn ${EMBEDDING_MODEL} \
  -i aap-product-docs-$(echo $AAP_VERSION | sed 's/\./_/g') \
  --vector-store-type=llamastack-faiss \
  -c 200 \
  -l 10

COPY tests ./tests
COPY pyproject.toml ./pyproject.toml
RUN python3.12 -m ensurepip --default-pip
RUN python3.12 -m pip install --no-cache-dir pytest
RUN PYTHONPATH=/rag-content TRANSFORMERS_OFFLINE=1 HF_HOME=/rag-content/embeddings_model REQUIRE_VECTOR_DB=1 python3.12 -m pytest tests/tests/test_vector_query.py -v -c pyproject.toml

WORKDIR /rag-content/llama_stack_vector_db
RUN gzip faiss_store.db; sha256sum faiss_store.db.gz > faiss_store.db.gz.sha256
RUN sed -n 's/.*vector_store_id: //p' llama-stack.yaml | tr -d '\n' > provider_vector_db_id.ind

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:8eb2830d0936237fc13a1f2f7e45aecf90d69043380ad167fad0343632937f41

# install diff and gzip
RUN microdnf install -y diffutils gzip

COPY --from=builder /rag-content/embeddings_model /rag/embeddings_model
COPY --from=builder /rag-content/llama_stack_vector_db /rag/llama_stack_vector_db

# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
RUN mkdir /licenses
COPY LICENSE /licenses/

# Labels for enterprise contract
LABEL com.redhat.component=aap-rag-content
LABEL description="Red Hat Ansible Automation Platform RAG content"
LABEL distribution-scope=private
LABEL io.k8s.description="Red Hat Ansible Automation Platform RAG content"
LABEL io.k8s.display-name="Ansible Automation Platform RAG content"
LABEL io.ansible.tags="ansible,aap,ai,assistant,rag"
LABEL name=aap-rag-content
LABEL release=0.0.1
LABEL url="https://github.com/ansible/aap-rag-content"
LABEL vendor="Red Hat"
LABEL version=0.0.1
LABEL summary="Red Hat Ansible Automation Platform RAG content"

COPY entrypoint.sh /rag
RUN chmod +x /rag/entrypoint.sh

USER 65532:65532
