[tool.ruff]

# description of all rules are available on https://docs.astral.sh/ruff/rules/
lint.select = ["D", "E", "F", "W", "C", "S", "I", "TCH", "SLOT", "RUF", "C90", "N", "YTT", "ASYNC", "TRIO"]

# we need to check 'mood' of all docstrings, this needs to be enabled explicitly
lint.extend-select = ["D401"]

lint.ignore = []

target-version = "py311"
lint.pydocstyle.convention = "google"
line-length = 100

[tool.mypy]
disable_error_code = ["union-attr", "return-value", "arg-type", "import-untyped"]
ignore_missing_imports = true

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "black==24.10.0",
    "mypy==1.15.0",
    "ruff==0.9.7",
    "types-requests==2.32.0.20241016"
]

[project.optional-dependencies]
cpu = [
    "torch @ https://download.pytorch.org/whl/cpu/torch-2.3.1%2Bcpu-cp311-cp311-linux_x86_64.whl",
    "faiss-cpu==1.9.0.post1",
]
gpu = [
    "torch==2.6.0",
    "faiss-gpu-cu12==1.10.0",
]

[project]
name = "aap-rag-content"
version = "0.1.0"
description = "RAG content for AAP chatbot"
authors = []
dependencies = [
    "PyYAML==6.0.2",
    "huggingface_hub==0.29.1",
    "llama_index==0.12.19",
    "llama-index-vector-stores-faiss==0.3.0",
    "llama-index-embeddings-huggingface==0.5.1",
    "llama-index-readers-file==0.4.5",
    "requests>=2.32.3",
    "llama-index-vector-stores-postgres>=0.4.2",
]
requires-python = "==3.11.*"
readme = "README.md"
license = "LICENSE"
